# 第4章 练习题
4.1 如图所示为二次四边形单元，试计算$\dfrac{\partial N_1}{\partial x}$和$\dfrac{\partial N_2}{\partial y}$在自然坐标为$\left(\dfrac{1}{2},\dfrac{1}{2}\right)$的点$Q$的数值（因为单元的边是直线，可用4个结点定义单元的几何形状）

<img src="../ex4_1.jpg", width="600">

In [18]:
# 导入模块
import numpy as np
import sympy as sm
import scipy as sp
import matplotlib.pyplot

## 坐标采用4个结点时

In [19]:
# 设全局坐标
(x1, y1) = (40, 50)
(x2, y2) = ( 5, 40)
(x3, y3) = (10, 10)
(x4, y4) = (30, 20)


In [20]:
x_crd = np.array([x1, x2, x3, x4])
y_crd = np.array([y1, y2, y3, y4])

XY=np.array([[x1,y1],\
             [x2,y2],\
             [x3,y3],\
             [x4,y4]])
XY

array([[40, 50],
       [ 5, 40],
       [10, 10],
       [30, 20]])

In [21]:
# 4个结点的局部坐标为

(xi1, et1) = ( 1, 1)
(xi2, et2) = (-1, 1)
(xi3, et3) = (-1,-1)
(xi4, et4) = ( 1,-1)

In [22]:
xi_crd = np.array([xi1, xi2, xi3, xi4])
et_crd = np.array([et1, et2, et3, et4])

坐标插值函数为
$$x=\sum_{i=1}^{4}{N_i(\xi,\eta)x_i},\qquad y=\sum_{i=1}^{4}{N_i(\xi,\eta)y_i}$$
其中
$$
\left\{
\begin{array}{rcl}
N_1(\xi, \eta) & = & \dfrac{1}{4}(1+\xi)(1+\eta)\\
N_2(\xi, \eta) & = & \dfrac{1}{4}(1-\xi)(1+\eta)\\
N_3(\xi, \eta) & = & \dfrac{1}{4}(1-\xi)(1-\eta)\\
N_4(\xi, \eta) & = & \dfrac{1}{4}(1+\xi)(1-\eta)
\end{array}
\right.
$$

In [24]:
# 4结点形函数
xi, et = sm.symbols('xi et')

N_1 = (1+xi)*(1+et)/4
N_2 = (1-xi)*(1+et)/4
N_3 = (1-xi)*(1-et)/4
N_4 = (1+xi)*(1-et)/4

N = [(1+xi_crd[i]*xi)*(1+et_crd[i]*et)/4 for i in range(4)]
N

[(et + 1)*(xi + 1)/4,
 (et + 1)*(-xi + 1)/4,
 (-et + 1)*(-xi + 1)/4,
 (-et + 1)*(xi + 1)/4]

偏导数关系式为
$$
  \left\{\begin{array}{c}
    \dfrac{\partial N_i}{\partial \xi}\\
    \dfrac{\partial N_i}{\partial \eta}
  \end{array}\right\}
  =
  \left(\begin{array}{cc}
    \dfrac{\partial x}{\partial \xi} & \dfrac{\partial y}{\partial \xi}\\
    \dfrac{\partial x}{\partial \eta} & \dfrac{\partial y}{\partial \eta}
  \end{array}\right)
  \left\{\begin{array}{c}
    \dfrac{\partial N_i}{\partial x}\\
    \dfrac{\partial N_i}{\partial y}
  \end{array}\right\}
  =\boldsymbol{J}
  \left\{\begin{array}{c}
    \dfrac{\partial N_i}{\partial x}\\
    \dfrac{\partial N_i}{\partial y}
  \end{array}\right\}
$$
其中，$\boldsymbol{J}$称为Jacobi矩阵，满足
$$
  \begin{array}{c}
    \boldsymbol{J}=\dfrac{\partial(x,y)}{\partial(\xi,\eta)}
    =
    \left(\begin{array}{cc}
      \sum\limits^m_{i=1}\dfrac{\partial N_i}{\partial \xi}x_i   & \sum\limits^m_{i=1}\dfrac{\partial N_i}{\partial \xi}y_i\\
      \sum\limits^m_{i=1}\dfrac{\partial N_i}{\partial \eta}x_i  & \sum\limits^m_{i=1}\dfrac{\partial N_i}{\partial \eta}y_i
    \end{array}\right)\\
    =
    \left(\begin{array}{cccc}
      \dfrac{\partial N_1}{\partial \xi}   & \dfrac{\partial N_2}{\partial \xi}   & \cdots & \dfrac{\partial N_m}{\partial \xi}\\
      \dfrac{\partial N_1}{\partial \eta}  & \dfrac{\partial N_2}{\partial \eta}  & \cdots & \dfrac{\partial N_m}{\partial \eta}
    \end{array}\right)
    \left(\begin{array}{cc}
      x_1    & y_1\\
      x_2    & y_2\\
      \vdots & \vdots\\
      x_m    & y_m
    \end{array}\right)
  = \boldsymbol{\partial N}\cdot\boldsymbol{XY}
\end{array}
$$

In [26]:
partial_N = np.array([[sm.diff(N_i, xi) for N_i in N], [sm.diff(N_i, et) for N_i in N]])
partial_N

array([[et/4 + 1/4, -et/4 - 1/4, et/4 - 1/4, -et/4 + 1/4],
       [xi/4 + 1/4, -xi/4 + 1/4, xi/4 - 1/4, -xi/4 - 1/4]], dtype=object)

In [6]:
Np = np.array([[sm.diff(N_i, xi).evalf(subs={xi:0.5, et:0.5}) for N_i in N], [sm.diff(N_i, et).evalf(subs={xi:0.5, et:0.5}) for N_i in N]])
Np

array([[0.375000000000000, -0.375000000000000, -0.125000000000000,
        0.125000000000000],
       [0.375000000000000, 0.125000000000000, -0.125000000000000,
        -0.375000000000000]], dtype=object)

In [27]:
J4 = np.dot(partial_N, XY)
J4

array([[15*et/4 + 55/4, 5],
       [15*xi/4 + 5/4, 15]], dtype=object)

In [8]:
#J4 = np.dot(Np, XY)
#J4

array([[15.6250000000000, 5.00000000000000],
       [3.12500000000000, 15.0000000000000]], dtype=object)

# 坐标采用8个结点时

In [28]:
# 设全局坐标
(x1, y1) = (40.0, 50.0)
(x2, y2) = ( 5.0, 40.0)
(x3, y3) = (10.0, 10.0)
(x4, y4) = (30.0, 20.0)
(x5, y5) = ((x1+x2)/2, (y1+y2)/2)
(x6, y6) = ((x2+x3)/2, (y2+y3)/2)
(x7, y7) = ((x3+x4)/2, (y3+y4)/2)
(x8, y8) = ((x4+x1)/2, (y4+y1)/2)

x_crd = np.array([x1, x2, x3, x4, x5, x6, x7, x8])
y_crd = np.array([y1, y2, y3, y4, y5, y6, y7, y8])

XY=np.array([[x1,y1],[x2,y2],[x3,y3],[x4,y4],[x5,y5],[x6,y6],[x7,y7],[x8,y8]])
XY

array([[40. , 50. ],
       [ 5. , 40. ],
       [10. , 10. ],
       [30. , 20. ],
       [22.5, 45. ],
       [ 7.5, 25. ],
       [20. , 15. ],
       [35. , 35. ]])

In [29]:
# 4个结点的局部坐标为
(xi1, et1) = ( 1, 1)
(xi2, et2) = (-1, 1)
(xi3, et3) = (-1,-1)
(xi4, et4) = ( 1,-1)
(xi5, et5) = ( 0, 1)
(xi6, et6) = (-1, 0)
(xi7, et7) = ( 0,-1)
(xi8, et8) = ( 1, 0)

xi_crd = np.array([xi1, xi2, xi3, xi4, xi5, xi6, xi7, xi8])
et_crd = np.array([et1, et2, et3, et4, et5, et6, et7, et8])

坐标插值函数为
$$x=\sum_{i=1}^{8}{N_i(\xi,\eta)x_i},\qquad y=\sum_{i=1}^{8}{N_i(\xi,\eta)y_i}$$
采用Serendipity单元建立形函数，如下
首先
$$
\left\{
\begin{array}{rcl}
\hat{N}_1(\xi, \eta) & = & \dfrac{1}{4}(1+\xi)(1+\eta)\\
\hat{N}_2(\xi, \eta) & = & \dfrac{1}{4}(1-\xi)(1+\eta)\\
\hat{N}_3(\xi, \eta) & = & \dfrac{1}{4}(1-\xi)(1-\eta)\\
\hat{N}_4(\xi, \eta) & = & \dfrac{1}{4}(1+\xi)(1-\eta)
\end{array}
\right.
$$
然后
$$
\left\{
\begin{array}{rcl}
N_5(\xi, \eta) & = & \dfrac{1}{2}(1-\xi^2)(1+\eta)\\
N_6(\xi, \eta) & = & \dfrac{1}{2}(1-\xi)(1-\eta^2)\\
N_7(\xi, \eta) & = & \dfrac{1}{2}(1-\xi^2)(1-\eta)\\
N_8(\xi, \eta) & = & \dfrac{1}{2}(1+\xi)(1-\eta^2)
\end{array}
\right.
$$
最后
$$
\left\{
\begin{array}{c}
N_1(\xi, \eta) = \hat{N}_1(\xi, \eta) - \sum_{i=5}^{8}{\hat{N}_1(\xi_i, \eta_i)N_i(\xi, \eta)}\\
N_2(\xi, \eta) = \hat{N}_2(\xi, \eta) - \sum_{i=5}^{8}{\hat{N}_2(\xi_i, \eta_i)N_i(\xi, \eta)}\\
N_3(\xi, \eta) = \hat{N}_3(\xi, \eta) - \sum_{i=5}^{8}{\hat{N}_3(\xi_i, \eta_i)N_i(\xi, \eta)}\\
N_4(\xi, \eta) = \hat{N}_4(\xi, \eta) - \sum_{i=5}^{8}{\hat{N}_4(\xi_i, \eta_i)N_i(\xi, \eta)}
\end{array}
\right.
$$


In [30]:
# 8结点形函数
xi, et = sm.symbols('xi et')

hN_1 = (1+xi)*(1+et)/4
hN_2 = (1-xi)*(1+et)/4
hN_3 = (1-xi)*(1-et)/4
hN_4 = (1+xi)*(1-et)/4

N_5 = (1-xi*xi)*(1+et)/2
N_6 = (1-xi)*(1-et*et)/2
N_7 = (1-xi*xi)*(1-et)/2
N_8 = (1+xi)*(1-et*et)/2

N = [0]*8
N[4:8] = [N_5, N_6, N_7, N_8]

hatN = [hN_1, hN_2, hN_3, hN_4]

#N_1 = hN_1 - sum([hN_1.evalf(subs={xi:xi_crd[i], et:et_crd[i]})*N[i] for i in range(4,8)])
#N_2 = hN_2 - sum([hN_2.evalf(subs={xi:xi_crd[i], et:et_crd[i]})*N[i] for i in range(4,8)])
#N_3 = hN_3 - sum([hN_3.evalf(subs={xi:xi_crd[i], et:et_crd[i]})*N[i] for i in range(4,8)])
#N_4 = hN_4 - sum([hN_4.evalf(subs={xi:xi_crd[i], et:et_crd[i]})*N[i] for i in range(4,8)])

#N[0:4] = [N_1, N_2, N_3, N_4]

N[0:4] = [hN -sum([hN.evalf(subs={xi:xi_crd[i], et:et_crd[i]})*N[i] for i in range(4,8)]) for hN in hatN]
sm.simplify(N)

[-0.e-143*(-et + 1)*(-xi**2 + 1) + (et + 1)*(xi + 1)/4 - 0.25*(et + 1)*(-xi**2 + 1) - 0.e-143*(-et**2 + 1)*(-xi + 1) - 0.25*(-et**2 + 1)*(xi + 1),
 -0.e-143*(-et + 1)*(-xi**2 + 1) + (et + 1)*(-xi + 1)/4 - 0.25*(et + 1)*(-xi**2 + 1) - 0.25*(-et**2 + 1)*(-xi + 1) - 0.e-143*(-et**2 + 1)*(xi + 1),
 (-et + 1)*(-xi + 1)/4 - 0.25*(-et + 1)*(-xi**2 + 1) - 0.e-143*(et + 1)*(-xi**2 + 1) - 0.25*(-et**2 + 1)*(-xi + 1) - 0.e-143*(-et**2 + 1)*(xi + 1),
 (-et + 1)*(xi + 1)/4 - 0.25*(-et + 1)*(-xi**2 + 1) - 0.e-143*(et + 1)*(-xi**2 + 1) - 0.e-143*(-et**2 + 1)*(-xi + 1) - 0.25*(-et**2 + 1)*(xi + 1),
 (et + 1)*(-xi**2 + 1)/2,
 (-et**2 + 1)*(-xi + 1)/2,
 (-et + 1)*(-xi**2 + 1)/2,
 (-et**2 + 1)*(xi + 1)/2]

In [31]:
partial_N = np.array([[sm.diff(N_i, xi) for N_i in N], [sm.diff(N_i, et) for N_i in N]])
partial_N

array([[0.25*et**2 + et/4 + 0.e-142*xi*(-et + 1) + 0.5*xi*(et + 1),
        -0.25*et**2 - et/4 + 0.e-142*xi*(-et + 1) + 0.5*xi*(et + 1),
        -0.25*et**2 + et/4 + 0.5*xi*(-et + 1) + 0.e-142*xi*(et + 1),
        0.25*et**2 - et/4 + 0.5*xi*(-et + 1) + 0.e-142*xi*(et + 1),
        -xi*(et + 1), et**2/2 - 1/2, -xi*(-et + 1), -et**2/2 + 1/2],
       [0.e-142*et*(-xi + 1) + 0.5*et*(xi + 1) + 0.25*xi**2 + xi/4,
        0.5*et*(-xi + 1) + 0.e-142*et*(xi + 1) + 0.25*xi**2 - xi/4,
        0.5*et*(-xi + 1) + 0.e-142*et*(xi + 1) - 0.25*xi**2 + xi/4,
        0.e-142*et*(-xi + 1) + 0.5*et*(xi + 1) - 0.25*xi**2 - xi/4,
        -xi**2/2 + 1/2, -et*(-xi + 1), xi**2/2 - 1/2, -et*(xi + 1)]],
      dtype=object)

In [13]:
Np = np.array([[sm.diff(N_i, xi).evalf(subs={xi:0.5, et:0.5}) for N_i in N], [sm.diff(N_i, et).evalf(subs={xi:0.5, et:0.5}) for N_i in N]])
Np

array([[0.562500000000000, 0.187500000000000, 0.187500000000000,
        0.0625000000000000, -0.750000000000000, -0.375000000000000,
        -0.250000000000000, 0.375000000000000],
       [0.562500000000000, 0.0625000000000000, 0.187500000000000,
        0.187500000000000, 0.375000000000000, -0.250000000000000,
        -0.375000000000000, -0.750000000000000]], dtype=object)

In [32]:
J8 = np.dot(partial_N, XY)
J8

array([[3.75*et + 13.75, 5.00000000000000],
       [3.75*xi + 1.25, 15.0000000000000]], dtype=object)

In [17]:
#J8 = np.dot(Np, XY)
#J8

In [33]:
sm.simplify(J8-J4)

[[0, 0], [0, 0]]